version: 0.2
phases:
  pre_build:
    commands:
      - echo prebuild phase
      - aws --version

  build:
    commands:

      # Check and deploy/update test-alb if changes are detected
      - echo checking changes for test-alb
      - aws cloudformation describe-stacks --stack-name test-alb >/dev/null 2>&1; then
        echo "Updating helper-stack..."
        aws cloudformation create-change-set --stack-name test-alb --template-url https://test--template.s3.amazonaws.com/test-alb.yml --change-set-name test-alb-changeset --capabilities CAPABILITY_NAMED_IAM --parameters ParameterKey=SSLCertificateID,ParameterValue=${SSLCertificateID} ParameterKey=VPC,ParameterValue=${VPC} ParameterKey=PublicSubnets,ParameterValue=${PublicSubnets} ParameterKey=LoadbalancerSecurityGroup,ParameterValue=${LoadbalancerSecurityGroup}
        aws cloudformation wait change-set-create-complete --stack-name test-alb --change-set-name helper-stack-changeset
        aws cloudformation describe-change-set --stack-name test-alb --change-set-name test-alb-changeset

artifacts:
  files:
    - "**/*"
