version: 0.2
phases:
  pre_build:
    commands:
      - echo "prebuild phase"
      - aws --version

  build:
    commands:
      - echo "running s3 sync command"
      - aws s3 sync ./ s3://${CLONE_TEMPLATE_BUCKET}/ --exclude "buildspec.yml"

      - echo $PublicSubnets
      # Execute external script
      # - echo "Running external script"
      # - chmod +x update_stacks.sh
      # - ./update_stacks.sh

artifacts:
  files:
    - "**/*"
